namespace Klinkby.Booqr.Core;

/// <summary>
///     Represents a tenant registration record from the central registry (<c>public.tenants</c>).
/// </summary>
/// <remarks>
///     Tenants are immutable registry entries containing the minimal information needed for host resolution.
///     Unlike business entities, tenants do not inherit audit timestamps; the registry tracks creation and modification separately.
/// </remarks>
/// <param name="Id">The unique tenant identifier, generated by the database identity sequence.</param>
/// <param name="Slug">The tenant's public subdomain label (e.g., "alice"), used for host-based routing.</param>
/// <param name="DbRole">The PostgreSQL login role name assigned to this tenant (e.g., "t_42"), derived deterministically from <paramref name="Id"/>.</param>
/// <param name="DisplayName">The tenant's display name for branding and public identification.</param>
public sealed record Tenant(int Id, string Slug, string DbRole, string DisplayName);

/// <summary>
///     Provides data access operations for tenant registry records.
/// </summary>
/// <remarks>
///     The tenant repository interfaces only with the <c>public.tenants</c> registry table
///     via the registry data source role (<c>booqr_registry</c>), which holds <c>SELECT</c> permission only.
///     This ensures tenant resolution never requires a tenant-scoped connection.
/// </remarks>
public interface ITenantRepository : IRepository
{
    /// <summary>
    ///     Resolves a tenant by its public slug.
    /// </summary>
    /// <param name="slug">The tenant's public subdomain label (e.g., "alice").</param>
    /// <param name="cancellation">The token used to propagate notification that the operation should be canceled.</param>
    /// <returns>
    ///     A task that represents the asynchronous operation. The task result contains the <see cref="Tenant"/> if found,
    ///     otherwise <c>null</c>.
    /// </returns>
    /// <remarks>
    ///     Returns <c>null</c> if the slug is not found or the tenant has been soft-deleted.
    ///     This method never uses a tenant-scoped connection; it queries the central registry only.
    /// </remarks>
    Task<Tenant?> GetBySlug(string slug, CancellationToken cancellation = default);
}
